name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Release
        uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npx semantic-release-plus --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}